# config.yml - Centralized configuration for wp-chat
# Cross-Encoder Reranker and Hybrid Search parameters

# Hybrid Search Configuration
hybrid:
  alpha: 0.6              # Dense weight (BM25 weight = 1 - alpha)
  k_bm25: 100             # BM25 retrieval count
  k_dense: 100            # Dense retrieval count

# MMR Diversification
mmr:
  lambda: 0.7             # Diversity vs relevance tradeoff (0.0-1.0)
  topn: 30               # Number of candidates for diversification

# Cross-Encoder Reranker
reranker:
  # Model selection strategy
  auto_detect: true              # Automatically detect CPU/GPU and select model
  fallback_to_cpu: true          # Fallback to CPU model if GPU fails

  # Available models
  models:
    cpu: "cross-encoder/ms-marco-MiniLM-L-6-v2"      # Lightweight CPU model
    gpu: "cross-encoder/ms-marco-MiniLM-L-12-v2"     # More accurate GPU model
    fallback: "cross-encoder/ms-marco-MiniLM-L-6-v2" # Fallback model

  # Performance settings
  batch_size: 16         # Batch size for efficient scoring
  timeout_sec: 5.0       # Timeout threshold for fallback
  device: null           # Device override (null = auto, "cpu", "cuda", "mps")

  # Composite scoring experiments
  composite_scoring:
    enabled: true        # Enable composite scoring experiments
    alpha: 0.8          # CE weight (hybrid weight = 1 - alpha)
    strategies:
      - name: "ce_only"     # Pure Cross-Encoder scoring
        alpha: 1.0
      - name: "hybrid_only" # Pure Hybrid scoring
        alpha: 0.0
      - name: "balanced"    # Balanced combination
        alpha: 0.5
      - name: "ce_heavy"    # CE-heavy combination
        alpha: 0.8

# API Configuration
api:
  topk_default: 5        # Default number of results
  topk_max: 10          # Maximum number of results
  snippet_length: 400   # Maximum snippet length for highlighting

  # Rate limiting configuration
  rate_limit:
    enabled: true       # Enable rate limiting
    max_requests: 100   # Max requests per window
    window_seconds: 3600 # Time window (1 hour)
    burst_limit: 20     # Burst requests allowed

  # Caching configuration
  cache:
    enabled: true       # Enable caching
    search_ttl: 1800   # Search results TTL (30 minutes)
    embedding_ttl: 7200 # Embeddings TTL (2 hours)
    max_size_mb: 100   # Maximum cache size

  # SLO monitoring configuration
  slo:
    enabled: true      # Enable SLO monitoring
    targets:
      search:
        p95_latency_ms: 800    # Target p95 latency
        success_rate: 0.995   # Target success rate (99.5%)
        window_minutes: 5     # Monitoring window
        alert_threshold: 0.9  # Alert threshold
      ask:
        p95_latency_ms: 1000   # Target p95 latency
        success_rate: 0.99     # Target success rate (99%)
        window_minutes: 5      # Monitoring window
        alert_threshold: 0.9   # Alert threshold

# Evaluation Configuration
eval:
  default_k: 5          # Default evaluation k
  queries_file: "eval/queries.jsonl"
